host: 127.0.0.1
port: 3000
server: "https://botsin.space"
client_id: "8exSqNUzpxWPGU1EFJyWbPGRAPChrqATLYoJ3_LvK0g"
client_secret: "BQXCTv5Q7HVkgyS5hpGvAV2ohiGjlwfNvbJKJx8W0OM"
email: "bitman101@gmail.com"
password: "DYO-vpn-aLz"
owner: "@0orpheus@niu.moe"
